name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        config: [Debug] # TODO: Add Release configuration, signing still makes issues

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup dependencies
        run: pwsh ./scripts/setup-dependencies.ps1 -SolutionDir ${{ github.workspace }}
        shell: pwsh
        working-directory: ${{ github.workspace }}

      - name: Build ${{ matrix.config }}
        run: |
          msbuild EduMFA-CredentialProvider.sln `
            /p:Configuration=${{ matrix.config }} `
            /p:Platform=x64 `
            /p:VisualStudioVersion=17.0 `
            /m `
            /v:minimal
        shell: pwsh
        working-directory: ${{ github.workspace }}
